

# This file was *autogenerated* from the file Challenges/Advanced/vote_for_pedro(150pts)/vote_calculator.sage
from sage.all_cmdline import *   # import sage library

_sage_const_256 = Integer(256); _sage_const_15 = Integer(15); _sage_const_3 = Integer(3)
from Crypto.Util.number import bytes_to_long

# message that the server is waiting for
m = b"VOTE FOR PEDRO"
m = bytes_to_long(m)

print(m)

# calculate the vote.

m = mod(m,_sage_const_256 **_sage_const_15 )
vote = m.nth_root(_sage_const_3 )
vote = int(vote)

print(vote)

